backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "assets/images/blog"
public_folder: "/assets/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["innovacion", "sostenibilidad", "tecnologia", "proyectos"]}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Blog Homepage"
        name: "blog-homepage"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}

  - name: "config"
    label: "Site Configuration"
    files:
      - file: "site-config.yml"
        label: "Site Configuration"
        name: "site-config"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Favicon", name: "favicon", widget: "image"}
          - {label: "Social Media", name: "social", widget: "object", fields: [
              {label: "Facebook", name: "facebook", widget: "string", required: false},
              {label: "Twitter", name: "twitter", widget: "string", required: false},
              {label: "LinkedIn", name: "linkedin", widget: "string", required: false},
              {label: "Instagram", name: "instagram", widget: "string", required: false}
            ]}

  - name: "categories"
    label: "Categories"
    folder: "_categories"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "category"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Color", name: "color", widget: "string", hint: "Hex color code (e.g., #003DA6)"}

  - name: "authors"
    label: "Authors"
    folder: "_authors"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "author"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Bio", name: "bio", widget: "text"}
      - {label: "Avatar", name: "avatar", widget: "image", required: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Social Media", name: "social", widget: "object", fields: [
          {label: "LinkedIn", name: "linkedin", widget: "string", required: false},
          {label: "Twitter", name: "twitter", widget: "string", required: false}
        ]}

  - name: "comments"
    label: "Comments"
    folder: "_comments"
    create: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "comment"}
      - {label: "Post ID", name: "post_id", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Content", name: "content", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Approved", name: "approved", widget: "boolean", default: false}

# Editor configuration
editor:
  preview: true
  frame: true

# UI customization
ui:
  # Customize the logo
  logo: "/assets/images/Ali_head.png"
  
  # Customize the colors
  colors:
    primary: "#003DA6"
    secondary: "#DB9500"
    accent: "#71B338"
  
  # Customize the fonts
  fonts:
    body: "Work Sans, sans-serif"
    heading: "Zilla Slab, serif"

# Custom widgets (if needed)
widgets:
  - name: "custom-select"
    widget: "select"
    options: ["option1", "option2", "option3"]
